[project]
name = "ub-hrpro-cl"
version = "0.1.0"
description = "Official PyTorch implementation of Point-Supervised Japanese Fingerspelling Localization via HR-Pro and Contrastive Learning."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
angle-features = [
    "mediapipe==0.10.21",
    "numpy==1.26.4",
]
dev = [
    "ruff>=0.12.1",
]
